include: package:very_good_analysis/analysis_options.9.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    always_use_package_imports: false
    literal_only_boolean_expressions: false
    require_trailing_commas: false
    comment_references: false
    only_throw_errors: false
    avoid_positional_boolean_parameters: false
    use_build_context_synchronously: false
    always_put_required_named_parameters_first: false
    use_late_for_private_fields_and_variables: false
    flutter_style_todos: false
    no_leading_underscores_for_local_identifiers: false
    avoid_catches_without_on_clauses: false
    document_ignores: false
    depend_on_referenced_packages: false
    avoid_setters_without_getters: false
   # avoid_dynamic_calls: false
